---
include:
  - { project: fsrvcorp/ci-templates, file: golang.yml }
  - { project: fsrvcorp/ci-templates, file: dependency-imp.yml }
  - { project: fsrvcorp/ci-templates, file: semantic-versioning.yml }
